packages:
  - "apps/*"
  - "packages/*"
overrides:
  ioredis: ^5.11.0
  react: 19.1.0
  react-dom: 19.1.0
allowBuilds:
  '@clerk/shared': true
  '@parcel/watcher': true
  '@sentry/cli': false
  '@swc/core': true
  core-js: false
  esbuild: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
